name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: List repo files (optional debug)
      - name: List repo files
        run: ls -R

      # Step 3: Save SSH key to a file
      - name: Save SSH key
        run: |
          echo "${{ secrets.SAI }}" > Sai.pem
          chmod 600 Sai.pem

      # Step 4: Copy files to EC2
      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DOCKER_S104_DEMO_MACHINE_HOST }}
          username: ubuntu
          key_path: Sai.pem        # use key file instead of secret string
          source: "./*"
          target: /home/ubuntu/ecommercefullstack

      # Step 5: SSH into EC2 and deploy with Docker Compose
      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DOCKER_S104_DEMO_MACHINE_HOST }}
          username: ubuntu
          key_path: Sai.pem        # use key file instead of secret string
          script_stop: true
          debug: true
          script: |
            cd ~/ecommercefullstack

            # Install Git if missing
            if ! command -v git &> /dev/null; then
              echo "Installing Git..."
              sudo apt-get update -y
              sudo apt-get install -y git
            fi

            # Install Docker if missing
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt-get update -y
              sudo apt-get install -y ca-certificates curl gnupg lsb-release

              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Stop old containers, rebuild, and restart
            sudo docker compose down
            sudo docker compose up -d --build
